### ISSUE TITLE
feat(range): allow to select a range of commits per repositories

### ISSUE THREAD

**Issue by FlorentinDUBOIS** [FlorentinDUBOIS/changelog#5]
This feature should be implement using the `policy.toml` file. It can be something like this:

```toml
[[repositories]]
name = "Changelog"
path = "."
scopes = [ ]
range = "HEAD..3af2afe"
```
